import turtle

arrow=turtle.Turtle()

arrow.color("blue","red")
arrow.begin_fill()
arrow.forward(100)
arrow.left(90)
arrow.forward(100)
arrow.left(90)
arrow.forward(100)
arrow.left(90)
arrow.forward(100)
arrow.left(90)
arrow.end_fill()

arrow.color("green","black")
arrow.begin_fill()
arrow.penup()
arrow.forward(200)
arrow.pendown()
arrow.forward(100)
arrow.left(90)
arrow.forward(100)
arrow.left(90)
arrow.forward(100)
arrow.left(90)
arrow.forward(100)
arrow.left(90)
arrow.end_fill()

turtle.done()